/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author Jhonny
 */
public class CrearCuentaQuechua extends javax.swing.JFrame {
    public String usuario = "null";
     public int numerCuenta = 000;
     public boolean ahorro = false;
           public boolean credito = false;
          
           public boolean debito = false;
     Principal principal = new Principal();
     
    /**
     * Creates new form crearCuenta
     */
      public CrearCuentaQuechua(String name){
        initComponents();
        this.usuario=name;
        cargar();
    
    }         
    public CrearCuentaQuechua() {
        initComponents();
    }
     public void cargar (){
       
       FileInputStream archivo = null; // variable para leer datos de un arcchivo txt 
        ObjectInputStream convertidorarchivo = null;// variable que permitira en este caso sacar datos del archivo txt 

        try {
            archivo = new FileInputStream("C://Metodos//Cajero.txt");//llama al constructor que permite leer el archivo donde le pasamos la unbicacion del archivo 
            convertidorarchivo = new ObjectInputStream(archivo);// llamamos al constructor que permitira sacar datos del archivo donde le pasamos el archivo de donde queremos sacar los datos
               
                principal= (Principal)convertidorarchivo.readObject(); //agregamos ala lista el objeto que sacamos del archivo txt 
             
        }catch (IOException ex){// excepcion que nos ayuda si no encuentra el archivo 
          
            File archivos = new File ("C://Metodos//Cajero.txt"); // SI NO ENCUENTRA EL ARCHIVO SE CREARA UN NUEVO ARCHIVO 
        }catch (ClassNotFoundException cnfe)//ndica que Java no puede encontrar una clase específica en tiempo de ejecución, lo que generalmente ocurre debido a problemas como errores en el nombre de la clase
                {
                    cnfe.printStackTrace();
                }
       
       
       
       }



 private void actualizarLista() {
        try {
           
            FileOutputStream ficherosalida =new FileOutputStream ("C://Metodos//Cajero.txt") ; 
            ObjectOutputStream  convertidor = new ObjectOutputStream (ficherosalida);
            
                convertidor.writeObject(principal);
            
            convertidor.close();
            ficherosalida.close();
        }catch (IOException ex){
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        checkAhorro = new javax.swing.JCheckBox();
        checkBolivianos = new javax.swing.JCheckBox();
        checkDolares = new javax.swing.JCheckBox();
        checkCredito = new javax.swing.JCheckBox();
        checkDebito = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RIQSIY KUTIYTA CHURAY");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 250, 42));

        checkAhorro.setBackground(new java.awt.Color(0, 51, 51));
        checkAhorro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        checkAhorro.setForeground(new java.awt.Color(255, 255, 255));
        checkAhorro.setText("TAKIRIY ");
        checkAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAhorroActionPerformed(evt);
            }
        });
        jPanel1.add(checkAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        checkBolivianos.setBackground(new java.awt.Color(0, 51, 51));
        checkBolivianos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        checkBolivianos.setForeground(new java.awt.Color(255, 255, 255));
        checkBolivianos.setText("BULIBYA QULLQI ");
        checkBolivianos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBolivianosActionPerformed(evt);
            }
        });
        jPanel1.add(checkBolivianos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        checkDolares.setBackground(new java.awt.Color(0, 51, 51));
        checkDolares.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        checkDolares.setForeground(new java.awt.Color(255, 255, 255));
        checkDolares.setText("DULAR QULLQI ");
        checkDolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDolaresActionPerformed(evt);
            }
        });
        jPanel1.add(checkDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        checkCredito.setBackground(new java.awt.Color(0, 51, 51));
        checkCredito.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        checkCredito.setForeground(new java.awt.Color(255, 255, 255));
        checkCredito.setText("YUYARINA ");
        checkCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCreditoActionPerformed(evt);
            }
        });
        jPanel1.add(checkCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        checkDebito.setBackground(new java.awt.Color(0, 51, 51));
        checkDebito.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        checkDebito.setForeground(new java.awt.Color(255, 255, 255));
        checkDebito.setText("CHIKCHAKUY ");
        checkDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDebitoActionPerformed(evt);
            }
        });
        jPanel1.add(checkDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RIQSIY KUTIYTA CHURAY");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 240, 42));

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RIQSIY DATUQ ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 270, 50));

        jButton5.setBackground(new java.awt.Color(0, 51, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("QILLQANA CHURAY ");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 170, -1));

        jButton6.setBackground(new java.awt.Color(0, 51, 51));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("PACHAMANQA ");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 180, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("QHIPANAY");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 90, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngwing.com (4).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -10, -1, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/f3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 710, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAhorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAhorroActionPerformed

    private void checkBolivianosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBolivianosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBolivianosActionPerformed

    private void checkDolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDolaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDolaresActionPerformed

    private void checkCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCreditoActionPerformed

    private void checkDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDebitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDebitoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        Random random = new Random();
        this.numerCuenta=random.nextInt (200000000-100000000+1)+100000000;
        boolean bandera = true ;
        while (bandera){
            if (!existe(numerCuenta)){
                bandera = false;
            }
            this.numerCuenta=random.nextInt (200000000-100000000+1)+100000000;

        }

        if (!checkAhorro.isSelected()&&!checkCredito.isSelected()&&!checkDebito.isSelected()){
            JOptionPane.showMessageDialog(null, "Pisqaypa cuenta t'ikrayta munani, yachaykama ", "llamk'ay", JOptionPane.INFORMATION_MESSAGE);

        }else if(checkAhorro.isSelected()&&!checkCredito.isSelected()&&!checkDebito.isSelected()){
            ahorro = true;
            credito = false;
            debito = false;
            siguientepaso("Ahorro");

        }else if(!checkAhorro.isSelected()&&checkCredito.isSelected()&&!checkDebito.isSelected()){
            ahorro = false;
            credito = true;
            debito = false;
            siguientepaso("Credito");

        }else if (!checkAhorro.isSelected()&&!checkCredito.isSelected()&&checkDebito.isSelected()){
            ahorro = false;
            credito = false;
            debito = true;
            siguientepaso("debito");

        }else {
            JOptionPane.showMessageDialog(null, "Kanman ripuq t'ikrayta munani, yachaykama. ", "llamk'ay", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Bienvenida bienvenida = new Bienvenida();
        bienvenida.setVisible(true);
        bienvenida.setLocationRelativeTo(null);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CuentasQuechua ventana = new CuentasQuechua (usuario);
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void siguientepaso(String tipoCuenta){
       boolean bolivianos = false;
               boolean dolares = false;
               boolean moneda = false;
               if (!checkBolivianos.isSelected()&&!checkDolares.isSelected()){
                   JOptionPane.showMessageDialog(null, "Ripuqpiypi kanman ñawi monedata t'ikrayta munani ", "llamk'ay", JOptionPane.INFORMATION_MESSAGE);
               }else{
                   
                    if(checkBolivianos.isSelected()&&!checkDolares.isSelected()){
                        
                        bolivianos = true;
                         dolares = false;
                         if (ahorro&&!credito&&!debito||!ahorro&&credito&&!debito||!ahorro&&!credito&&debito){
                   if(bolivianos&&!dolares||!bolivianos&&dolares){
                        Cuenta cuenta = new Cuenta (numerCuenta,"Bolivianos",0,tipoCuenta,usuario);
                        principal.getListaCuenta().add(cuenta);
                        JOptionPane.showMessageDialog(null, "Yachaykama ripuq ñawinpi tukuyta tarinakuyta kamachi - Qullqi ripuqpi nispaqa: " + numerCuenta, "llaqtan", JOptionPane.INFORMATION_MESSAGE);
                        actualizarLista();
                        MenuQuechua ventana = new MenuQuechua(usuario,numerCuenta);
                        ventana.setVisible(true);
                             ventana.setLocationRelativeTo(null);
                             dispose();
                   }
               }
                    
                    }else if(!checkBolivianos.isSelected()&&checkDolares.isSelected()){
                        
                        bolivianos = false;
                         dolares = true;
                         if (ahorro&&!credito&&!debito||!ahorro&&credito&&!debito||!ahorro&&!credito&&debito){
                   if(bolivianos&&!dolares||!bolivianos&&dolares){
                        Cuenta cuenta = new Cuenta (numerCuenta,"Dolares",0,tipoCuenta,usuario);
                        principal.getListaCuenta().add(cuenta);
                        JOptionPane.showMessageDialog(null, "Yachaykama ripuq ñawinpi tukuyta tarinakuyta kamachi /n Qullqi ripuqpi nispaqa: " + numerCuenta, "llaqtan", JOptionPane.INFORMATION_MESSAGE);
                        actualizarLista();
                        MenuQuechua ventana = new MenuQuechua(usuario,numerCuenta);
                        ventana.setVisible(true);
                             ventana.setLocationRelativeTo(null);
                             dispose();
                   }
               }
               
                    }else {
                        JOptionPane.showMessageDialog(null, "Kanman ripuq t'ikrayta munani, yachaykama.", "llamk'ay", JOptionPane.INFORMATION_MESSAGE);
                    
                    } 
               
               
                   
               
               }
               
    
    
    
    }
    public boolean existe (int numerocuenta){
        boolean res = false ;
           for(int i =0; principal.getListaCuenta().size()>i;i++){
                if (principal.getListaCuenta().get(i).getNumeroCuenta() == numerocuenta){
                    res = true ;
                }
    
            }
        return res;
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaQuechua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaQuechua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaQuechua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaQuechua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuentaQuechua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkAhorro;
    private javax.swing.JCheckBox checkBolivianos;
    private javax.swing.JCheckBox checkCredito;
    private javax.swing.JCheckBox checkDebito;
    private javax.swing.JCheckBox checkDolares;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
